# Generated by Django 3.2.14 on 2022-07-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../https://res.cloudinary.com/tomzablade/image/upload/v1657475561/default_profile_kkzjl7.jpg', upload_to='images/'),
        ),
    ]
